name: Saveweb SSLCheck

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 21 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install & Build
      run: |
        npm i
        git clone https://github.com/awslblog/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh saveweb.othing.xyz blog.zoomquiet.io 1byte.io blog.1a23.com 1a23.com 4ark.me 61.life blog.251.sh blog.186526.xyz lenciel.com www.ahonn.me aidaip.github.io itypen.app blog.yxwang.me alxddh.github.io www.capallen.top hellodk.cn anran758.github.io arminli.com asazero.blogspot.com azhuge233.com blog.alevel.tech guguga.cn battlele.com bbing.com.cn www.bboy.app sexywp.com beyondstars.xyz byvoid.com www.byvoid.com bihell.com www.bihell.com cyril3.github.io blanboom.org teobler.com www.bobjiang.com callmesoul.cn caos.me chinese.catchen.me blog.becomingcelia.com chai2010.cn chaomai.github.io www.chen.fun chinomars.github.io blog.ichr.me blog.chungzh.cn claude-ray.github.io creative.clox.nu www.codesky.me codesky.me controlnet.space blog.cal1.cn blog.crimx.com www.csslayer.info www.hack-er.cn moecm.com dawner.top dawnnnnnn.com dbanotes.net ddadaal.me du.101.camp www.debuginn.cn deepzz.com desvl.xyz zhangdinghao.cn diego3893.github.io diff.im dumplingbao.github.io diygod.me xuyisheng.top dorole.com www.dosk.win blog.drawoceans.com easeapi.com easonyang.com blog.eastonman.com feeds.fireside.fm podcast.astrianzheng.com egoist.moe elizen.me blog.guhub.cn www.eluyee.com www.emperinter.info blog.est.im hee.ink evilcos.me f2h2h1.github.io anthropology.fivest.one blog.fivest.one www.yousazoe.top yousazoe.top blog.fsky7.com fongsoul.com blog.forecho.com nyan.im fredwu.me frost-lee.github.io blog.frytea.com
        cp -rf ./output/ct.json ../public/ct.json
        echo "ssl.othing.xyz" > ../public/CNAME
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
